#!/bin/zsh

# ==============================================
# Author: James Richardson
# Email: james.richardson@invertedlight.com

# Description:
# < Description of what is this script for >
# Usage:
# < How to use this script, flag usage or ... >
# ==============================================

# ============= Start of Code ==================

set -g default-terminal "screen-256color"
set -g focus-events on

