#!/bin/bash

# ==============================================
# Author: James Richardson
# Email: james.richardson@invertedlight.com

# Description:
# < Description of what is this script for >
# Usage:
# < How to use this script, flag usage or ... >
# ==============================================

# ============= Start of Code ==================

set editing-mode vi
set show-mode-in-prompt on

