[tools]
bat = "latest"
chezmoi = "latest"
starship = "latest"
vim = "latest"
"github:wezterm/wezterm" = { version = "latest", asset_pattern = "wezterm-*.Ubuntu22.04.tar.xz", bin_path = "wezterm/usr/bin", os = ["linux"] }
