#!/bin/bash

set -euo pipefail

if command -v zsh >/dev/null; then 
  sudo chsh -s $ (command -v zsh) $USER
fi

if [! -d "$HOME/.zsh" ]; then 
  mkdir -p "$HOME/.zsh"
fi

if [! -d "$HOME/.zsh/pure" ]; then
  git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
fi

sh -c "$(curl -fLS get.chezmoi.io)" -- init --apply git@github.com:Invertedlight/dotfiles.git
fi

git config --global user.name "Invertedlight"
git config --global user.email "james.richardson@invertedlight.com"

exit 0

