[tools]
bat = "latest"
chezmoi = "latest"
starship = "latest"
lsd = "latest"
fzf = "latest"
fd = "latest"
lazygit = "latest"
rg = "latest"
neovim = "latest"
node = "latest"
usage = "latest"
ripgrep = "latest"
direnv = "latest"
kubectl = "latest"
flux2 = "latest"
helm = "latest"
kustomize = "latest"
k9s = "latest"
sops = "latest"
age = "latest"
tmux = "latest"
"github:wezterm/wezterm" = { version = "latest", asset_pattern = "wezterm-*.Ubuntu22.04.tar.xz", bin_path = "wezterm/usr/bin", os = ["linux"] }
