#!/bin/bash

if [[ "$(uname -s)" == "Darwin" ]]; then
    /$HOME/.local/bin/mise trust /workspaces/$DEVPOD_WORKSPACE_ID/mise.toml && /$HOME/.local/bin/mise install
else
    /usr/local/bin/mise trust /workspaces/$DEVPOD_WORKSPACE_ID/mise.toml && /usr/local/bin/mise install
fi

